CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE productos (
  id bigint PRIMARY KEY,
  nombre text NOT NULL,
  precio numeric(10,2) NOT NULL,
  descripcion text NOT NULL,
  embedding vector(3072)
);

CREATE OR REPLACE FUNCTION match_productos(
  query_embedding vector(3072),
  match_count int DEFAULT 10
)
RETURNS TABLE (
  id bigint,
  nombre text,
  precio numeric,
  descripcion text,
  similarity float
)
LANGUAGE sql STABLE AS $$
  SELECT
    id,
    nombre,
    precio,
    descripcion,
    1 - (productos.embedding <=> query_embedding) AS similarity
  FROM productos
  ORDER BY productos.embedding <=> query_embedding
  LIMIT match_count;
$$;


CREATE OR REPLACE FUNCTION generar_embeddings_productos()
RETURNS TABLE (producto_id bigint, texto text)
AS $$
BEGIN
    RETURN QUERY
    SELECT p.id AS producto_id,
           p.nombre || '. ' || COALESCE(p.descripcion, '') AS texto
    FROM productos AS p
    WHERE p.embedding IS NULL;
END;
$$ LANGUAGE plpgsql;





INSERT INTO productos (id,nombre,precio,descripcion) 
VALUES
(1,'Clavo',107,'Clavo de acero para uso general.'),
(2,'Tarugo',114,'Tarugo plástico para pared.'),
(3,'Llave inglesa',121,'Llave ajustable de boca móvil.'),
(4,'Pinza pico de loro',128,'Pinza con ajuste múltiple.'),
(5,'Tenaza',135,'Herramienta para cortar y sujetar.'),
(6,'Martillo',142,'Martillo de carpintero cabeza metálica.'),
(7,'Serrucho',149,'Serrucho manual para madera.'),
(8,'Destornillador plano',156,'Destornillador de punta plana.'),
(9,'Destornillador phillips',163,'Destornillador de punta cruz.'),
(10,'Cinta métrica',170,'Cinta retráctil de medición 5m.'),
(11,'Nivel de burbuja',177,'Nivel para medir alineación.'),
(12,'Adhesivo epoxi',184,'Pegamento epoxi de alta resistencia.'),
(13,'Silicona',191,'Sellador de silicona neutra.'),
(14,'Llave allen set',198,'Juego de llaves allen hexagonales.'),
(15,'Cutter',205,'Cuchilla retráctil para cortes finos.'),
(16,'Alicate de corte',212,'Alicate para corte de cables.'),
(17,'Enchufe macho',219,'Enchufe eléctrico estándar 220V.'),
(18,'Enchufe hembra',226,'Toma hembra para conexión eléctrica.'),
(19,'Toma corriente',233,'Toma de pared 220V doble.'),
(20,'Tornillo',240,'Paquete de tornillos estándar para múltiples usos.'),
(21,'Clavo',247,'Clavo de acero para uso general.'),
(22,'Tarugo',254,'Tarugo plástico para pared.'),
(23,'Llave inglesa',261,'Llave ajustable de boca móvil.'),
(24,'Pinza pico de loro',268,'Pinza con ajuste múltiple.'),
(25,'Tenaza',275,'Herramienta para cortar y sujetar.'),
(26,'Martillo',282,'Martillo de carpintero cabeza metálica.'),
(27,'Serrucho',289,'Serrucho manual para madera.'),
(28,'Destornillador plano',296,'Destornillador de punta plana.'),
(29,'Destornillador phillips',103,'Destornillador de punta cruz.'),
(30,'Cinta métrica',110,'Cinta retráctil de medición 5m.'),
(31,'Nivel de burbuja',117,'Nivel para medir alineación.'),
(32,'Adhesivo epoxi',124,'Pegamento epoxi de alta resistencia.'),
(33,'Silicona',131,'Sellador de silicona neutra.'),
(34,'Llave allen set',138,'Juego de llaves allen hexagonales.'),
(35,'Cutter',145,'Cuchilla retráctil para cortes finos.'),
(36,'Alicate de corte',152,'Alicate para corte de cables.'),
(37,'Enchufe macho',159,'Enchufe eléctrico estándar 220V.'),
(38,'Enchufe hembra',166,'Toma hembra para conexión eléctrica.'),
(39,'Toma corriente',173,'Toma de pared 220V doble.'),
(40,'Tornillo',180,'Paquete de tornillos estándar para múltiples usos.'),
(41,'Clavo',187,'Clavo de acero para uso general.'),
(42,'Tarugo',194,'Tarugo plástico para pared.'),
(43,'Llave inglesa',201,'Llave ajustable de boca móvil.'),
(44,'Pinza pico de loro',208,'Pinza con ajuste múltiple.'),
(45,'Tenaza',215,'Herramienta para cortar y sujetar.'),
(46,'Martillo',222,'Martillo de carpintero cabeza metálica.'),
(47,'Serrucho',229,'Serrucho manual para madera.'),
(48,'Destornillador plano',236,'Destornillador de punta plana.'),
(49,'Destornillador phillips',243,'Destornillador de punta cruz.'),
(50,'Cinta métrica',250,'Cinta retráctil de medición 5m.'),
(51,'Nivel de burbuja',257,'Nivel para medir alineación.'),
(52,'Adhesivo epoxi',264,'Pegamento epoxi de alta resistencia.'),
(53,'Silicona',271,'Sellador de silicona neutra.'),
(54,'Llave allen set',278,'Juego de llaves allen hexagonales.'),
(55,'Cutter',285,'Cuchilla retráctil para cortes finos.'),
(56,'Alicate de corte',292,'Alicate para corte de cables.'),
(57,'Enchufe macho',299,'Enchufe eléctrico estándar 220V.'),
(58,'Enchufe hembra',106,'Toma hembra para conexión eléctrica.'),
(59,'Toma corriente',113,'Toma de pared 220V doble.'),
(60,'Tornillo',120,'Paquete de tornillos estándar para múltiples usos.'),
(61,'Clavo',127,'Clavo de acero para uso general.'),
(62,'Tarugo',134,'Tarugo plástico para pared.'),
(63,'Llave inglesa',141,'Llave ajustable de boca móvil.'),
(64,'Pinza pico de loro',148,'Pinza con ajuste múltiple.'),
(65,'Tenaza',155,'Herramienta para cortar y sujetar.'),
(66,'Martillo',162,'Martillo de carpintero cabeza metálica.'),
(67,'Serrucho',169,'Serrucho manual para madera.'),
(68,'Destornillador plano',176,'Destornillador de punta plana.'),
(69,'Destornillador phillips',183,'Destornillador de punta cruz.'),
(70,'Cinta métrica',190,'Cinta retráctil de medición 5m.'),
(71,'Nivel de burbuja',197,'Nivel para medir alineación.'),
(72,'Adhesivo epoxi',204,'Pegamento epoxi de alta resistencia.'),
(73,'Silicona',211,'Sellador de silicona neutra.'),
(74,'Llave allen set',218,'Juego de llaves allen hexagonales.'),
(75,'Cutter',225,'Cuchilla retráctil para cortes finos.'),
(76,'Alicate de corte',232,'Alicate para corte de cables.'),
(77,'Enchufe macho',239,'Enchufe eléctrico estándar 220V.'),
(78,'Enchufe hembra',246,'Toma hembra para conexión eléctrica.'),
(79,'Toma corriente',253,'Toma de pared 220V doble.'),
(80,'Tornillo',260,'Paquete de tornillos estándar para múltiples usos.'),
(81,'Clavo',267,'Clavo de acero para uso general.'),
(82,'Tarugo',274,'Tarugo plástico para pared.'),
(83,'Llave inglesa',281,'Llave ajustable de boca móvil.'),
(84,'Pinza pico de loro',288,'Pinza con ajuste múltiple.'),
(85,'Tenaza',295,'Herramienta para cortar y sujetar.'),
(86,'Martillo',102,'Martillo de carpintero cabeza metálica.'),
(87,'Serrucho',109,'Serrucho manual para madera.'),
(88,'Destornillador plano',116,'Destornillador de punta plana.'),
(89,'Destornillador phillips',123,'Destornillador de punta cruz.'),
(90,'Cinta métrica',130,'Cinta retráctil de medición 5m.'),
(91,'Nivel de burbuja',137,'Nivel para medir alineación.'),
(92,'Adhesivo epoxi',144,'Pegamento epoxi de alta resistencia.'),
(93,'Silicona',151,'Sellador de silicona neutra.'),
(94,'Llave allen set',158,'Juego de llaves allen hexagonales.'),
(95,'Cutter',165,'Cuchilla retráctil para cortes finos.'),
(96,'Alicate de corte',172,'Alicate para corte de cables.'),
(97,'Enchufe macho',179,'Enchufe eléctrico estándar 220V.'),
(98,'Enchufe hembra',186,'Toma hembra para conexión eléctrica.'),
(99,'Toma corriente',193,'Toma de pared 220V doble.'),
(100,'Tornillo',200,'Paquete de tornillos estándar para múltiples usos.'),
(101,'Taladro eléctrico',315,'Taladro percutor 650W con velocidad variable.'),
(102,'Amoladora angular',328,'Amoladora 4.5 pulgadas 750W.'),
(103,'Sierra circular',341,'Sierra circular 7.25 pulgadas 1400W.'),
(104,'Lijadora orbital',354,'Lijadora eléctrica orbital 200W.'),
(105,'Soplete',367,'Soplete a gas para soldadura y calor.'),
(106,'Pistola de calor',380,'Pistola térmica 2000W con regulador.'),
(107,'Remachadora',393,'Remachadora manual de palanca.'),
(108,'Grampadora',406,'Grampadora manual para tapicería.'),
(109,'Escuadra carpintero',419,'Escuadra metálica 30cm precisión.'),
(110,'Compás',432,'Compás de precisión para trazado.'),
(111,'Formón',445,'Formón de acero para madera 1 pulgada.'),
(112,'Cincel',458,'Cincel plano punta templada 3/4 pulgada.'),
(113,'Prensa manual',471,'Prensa tipo C apertura 4 pulgadas.'),
(114,'Gramil',484,'Gramil de carpintero ajustable.'),
(115,'Cepillo carpintero',497,'Cepillo manual para alisar madera.'),
(116,'Lima plana',510,'Lima bastarda plana 10 pulgadas.'),
(117,'Lima redonda',523,'Lima redonda para metales 8 pulgadas.'),
(118,'Escofina',536,'Escofina semicircular grano grueso.'),
(119,'Arco sierra',549,'Arco de sierra ajustable para metal.'),
(120,'Hojas sierra',562,'Pack 10 hojas sierra para metal.'),
(121,'Cable eléctrico',575,'Cable eléctrico 2x1.5mm rollo 10m.'),
(122,'Cinta aislante',588,'Cinta aislante eléctrica negra 20m.'),
(123,'Interruptor simple',101,'Interruptor de luz simple 10A.'),
(124,'Interruptor doble',114,'Interruptor doble independiente 10A.'),
(125,'Disyuntor',127,'Disyuntor diferencial 25A 30mA.'),
(126,'Termomagnética',140,'Llave termomagnética bipolar 20A.'),
(127,'Caja distribución',153,'Caja de distribución 12 módulos.'),
(128,'Zapatilla eléctrica',166,'Zapatilla 6 tomas con cable 3m.'),
(129,'Prolongador',179,'Prolongador eléctrico 10m naranja.'),
(130,'Bornera',192,'Bornera de conexión 12 posiciones.'),
(131,'Conector rápido',205,'Conector rápido empalme cables.'),
(132,'Canaleta',218,'Canaleta plástica adhesiva 2m.'),
(133,'Caño corrugado',231,'Caño corrugado flexible 3/4 pulgada.'),
(134,'Abrazadera',244,'Abrazadera metálica ajustable universal.'),
(135,'Broca metal',257,'Juego 13 brocas HSS para metal.'),
(136,'Broca madera',270,'Juego 8 brocas planas para madera.'),
(137,'Broca concreto',283,'Juego 5 brocas widia para concreto.'),
(138,'Mecha copa',296,'Mecha copa bimetálica 2 pulgadas.'),
(139,'Disco corte',309,'Disco de corte para amoladora 115mm.'),
(140,'Disco desbaste',322,'Disco desbaste metal 115mm.'),
(141,'Disco diamantado',335,'Disco diamantado para cerámica 115mm.'),
(142,'Lija papel',348,'Pack 10 lijas papel grano 120.'),
(143,'Lija tela',361,'Lija tela esmeril grano 80 rollo.'),
(144,'Espátula',374,'Espátula metálica flexible 4 pulgadas.'),
(145,'Llana',387,'Llana dentada para adhesivo cerámica.'),
(146,'Balde',400,'Balde plástico resistente 20 litros.'),
(147,'Brocha',413,'Brocha pintura mango madera 3 pulgadas.'),
(148,'Rodillo',426,'Rodillo pintura lana con mango.'),
(149,'Bandeja pintura',439,'Bandeja plástica para rodillo.'),
(150,'Masilla',452,'Masilla enduido interior balde 4kg.'),
(151,'Yeso',465,'Yeso en polvo bolsa 25kg.'),
(152,'Cemento cola',478,'Adhesivo cementicio para cerámicos 30kg.'),
(153,'Pastina',491,'Pastina para juntas cerámica blanca 5kg.'),
(154,'Impermeabilizante',504,'Membrana líquida impermeabilizante 20kg.'),
(155,'Barniz',517,'Barniz marino brillante 1 litro.'),
(156,'Diluyente',530,'Diluyente sintético 1 litro.'),
(157,'Aguarrás',543,'Aguarrás mineral 1 litro.'),
(158,'Removedor',556,'Removedor de pinturas gel 500ml.'),
(159,'Lija agua',569,'Lija al agua grano 400 pack 5.'),
(160,'Guantes látex',582,'Guantes látex descartables caja 100.'),
(161,'Guantes cuero',595,'Guantes cuero reforzados soldador.'),
(162,'Antiparras',108,'Antiparras protección transparentes.'),
(163,'Barbijo',121,'Barbijo doble filtro vapores.'),
(164,'Tapones oído',134,'Tapones auditivos espuma pack 10.'),
(165,'Casco obra',147,'Casco de seguridad ajustable.'),
(166,'Arnés seguridad',160,'Arnés de seguridad altura 5 puntos.'),
(167,'Escalera tijera',173,'Escalera tijera aluminio 6 escalones.'),
(168,'Escalera extensible',186,'Escalera extensible aluminio 4m.'),
(169,'Andamio',199,'Andamio tubular módulo básico.'),
(170,'Carretilla',212,'Carretilla construcción rueda inflable.'),
(171,'Pala',225,'Pala punta redonda mango madera.'),
(172,'Pico',238,'Pico doble uso construcción.'),
(173,'Azada',251,'Azada para jardinería y obra.'),
(174,'Rastrillo',264,'Rastrillo metálico 14 dientes.'),
(175,'Manguera',277,'Manguera reforzada 1/2 pulgada 20m.'),
(176,'Regadera',290,'Regadera plástica 10 litros.'),
(177,'Aspersor',303,'Aspersor giratorio para jardín.'),
(178,'Tijera podar',316,'Tijera de podar bypass profesional.'),
(179,'Motosierra',329,'Motosierra eléctrica 2000W 16 pulgadas.'),
(180,'Sopladora',342,'Sopladora hojas eléctrica 600W.'),
(181,'Cortacésped',355,'Cortadora césped eléctrica 1400W.'),
(182,'Bordeadora',368,'Bordeadora eléctrica 450W.'),
(183,'Hidrolavadora',381,'Hidrolavadora 1600PSI 1400W.'),
(184,'Compresor',394,'Compresor aire 50L 2.5HP.'),
(185,'Pistola pintar',407,'Pistola para pintar gravedad HVLP.'),
(186,'Inflador',420,'Inflador neumático con manómetro.'),
(187,'Llave impacto',433,'Llave de impacto neumática 1/2.'),
(188,'Engrasadora',446,'Engrasadora manual palanca 500cc.'),
(189,'Gato hidráulico',459,'Gato hidráulico botella 2 toneladas.'),
(190,'Soportes caballete',472,'Par caballetes metálicos plegables.'),
(191,'Banco trabajo',485,'Banco de trabajo madera con morsa.'),
(192,'Caja herramientas',498,'Caja herramientas plástica 3 niveles.'),
(193,'Organizador',511,'Organizador pared ganchos múltiples.'),
(194,'Linterna LED',524,'Linterna recargable LED 1000 lúmenes.'),
(195,'Detector metales',537,'Detector de metales portátil.'),
(196,'Medidor láser',550,'Medidor láser distancia 40m.'),
(197,'Nivel láser',563,'Nivel láser autonivelante cruz.'),
(198,'Termómetro',576,'Termómetro infrarrojo sin contacto.'),
(199,'Multímetro',589,'Multímetro digital profesional.'),
(200,'Pinza amperimétrica',102,'Pinza amperimétrica digital 600A.');